### PR TITLE
Various cleanups

### PR DESCRIPTION
**Pull request by aboodman**
Hey Brian, here are a number of suggested cleanups. There is a lot of mechanical cleanup of warnings and running prettier. I've put these in separate patches so they are easy to review.

The main thing is simplifying mutators.ts. I changed it to just treat everything as a dumb json object and do patches.

### CODE REVIEW

**Comment by BrianHung** [comment]
> The main thing is simplifying mutators.ts. I changed it to just treat everything as a dumb json object and do patches.

I had also thought about treating the store diffs as json patches, but do you think it captures intent better than manually craft mutators back out from diffs?

**Comment by aboodman** [comment]
Well the purpose of capturing intent is to enable more complex mutations. But right now this doesn't really have any more complex mutations. I think it's totally fine to use patches for the basic crud operations that are common in apps.

**Comment by aboodman** [comment]
(The one thing it had before was moving objects by delta, so that, ie, two people moving a shape could have their movements combined. That was cool, but in practice I think it is weird to have more than one user able to move a shape at the same time)

**Comment by BrianHung** [comment]
> but in practice I think it is weird to have more than one user able to move a shape at the same time

Agreed; important part is that individual props can be written to independently. Think we can wait for tldraw to emit CRUD commands instead of state diffs before re-visiting this.

**Pull request merged**
